apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-debug-files
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-debug-files
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-debug
  template:
    metadata:
      labels:
        app: kafka-debug
    spec:
      containers:
      - name: kafak-debug
        image: bargovic/kafka-debug:1.0.7-arm64
        volumeMounts:
        - name: pvc-debug-files
          mountPath: "/mnt/data/debug-secrets"
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "cp /mnt/data/debug-secrets/config /home/appuser/.kube/config" ]
      volumes:
        - name: pvc-debug-files
          projected:
            sources:
              - secret:
                  name: debug-secrets



